# Start

In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import json #for reading and writing JSON-encoded data.
# import re
from sklearn.preprocessing import LabelEncoder #for encoding categorical labels with numerical values. 

import numpy as np #for large, multi-dimensional arrays and matrices

from tensorflow.keras.utils import to_categorical # to convert integer-encoded categorical labels into one-hot encoded format.

from tensorflow.keras.preprocessing.text import Tokenizer #for tokenizing text data
# It converts text into sequences of integers, where each integer represents a unique token.

from tensorflow.keras.preprocessing.sequence import pad_sequences # to pad sequences of varying lengths to ensure uniformity.



# Reading data

In [3]:
#opens the JSON file in read mode and loads its contents into dictionary named data
with open('intents.json') as file:
  data = json.load(file)

In [ ]:
data

In [4]:
training_examples = [] #A list containing lowercase versions of all training examples extracted from the JSON data.
training_tags = [] #A list containing the tags associated with each training example.
responses = [] #A list containing the responses associated with each training example.

for example in data['intents']:
  for pattern in example['patterns']:
    training_examples.append(pattern.lower())
    training_tags.append(example['tag'])
    responses.append(example['responses'])

In [44]:
np.shape(training_examples)
training_examples

['hi',
 'how are you?',
 'is anyone there?',
 'hello',
 'good day',
 "what's up",
 'how are ya',
 'heyy',
 'whatsup',
 '??? ??? ??',
 'cya',
 'see you',
 'bye bye',
 'see you later',
 'goodbye',
 'i am leaving',
 'bye',
 'have a good day',
 'talk to you later',
 'ttyl',
 'i got to go',
 'gtg',
 'what is the name of your developers',
 'what is the name of your creators',
 'what is the name of the developers',
 'what is the name of the creators',
 'who created you',
 'your developers',
 'your creators',
 'who are your developers',
 'developers',
 'you are made by',
 'you are made by whom',
 'who created you',
 'who create you',
 'creators',
 'who made you',
 'who designed you',
 'name',
 'your name',
 'do you have a name',
 'what are you called',
 'what is your name',
 'what should i call you',
 'whats your name?',
 'what are you',
 'who are you',
 'who is this',
 'what am i chatting to',
 'who am i taking to',
 'what are you',
 'timing of college',
 'what is college timing',
 'working d

In [19]:
np.shape(training_tags)

(405, 38)

In [22]:
responses

[['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'],
 ['Sad to see you go :(', 'Talk to you later', 'Goodbye!', 'Come back soon'],
 ['Sad to see you go :(', 'Talk to you later', 'Goodbye!', 'Come back soon'],
 ['Sad to see you go :(', 'Talk to you later', 'Goodbye!', 'Come back soon'],
 ['Sad to see you go :(', 'Talk to you later', 'Goodbye!', 'Come back soon'],
 ['Sad t

In [5]:
# encode the categorical training tags into numerical labels.
le = LabelEncoder()
le.fit(training_tags)
training_tags = le.fit_transform(training_tags)
print(training_tags)

[14 14 14 14 14 14 14 14 14 14 13 13 13 13 13 13 13 13 13 13 13 13  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6 23 23 23 23 23 23 23 23 23 23
 23 23 23 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 24 24 24 24
 24 24 24 24 24 24 24 24 24 24 24  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5 11 11 11 11 11 11 11 11 11 11
 11 11 11 11 11 11 11 11 11 11 11 11 11 21 21 21 21 21 21 21 21 21 21 21
 21 21 21 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16
 16  8  8  8  8  8  8  8  8  8  8  8  7  7  7  7  7  7  7  7  7  7  7  7
  7 12 12 12 12 12 12 12 34 34 34 34 34 34 34 20 20 20 20 20 20 20 20 20
 20 20 20 20 20 18 18 18  1  1  1  1  1  1  1  1  1  1  1 22 22 22 22 22
 22 22 25 25 25 25 25 25 25 25 25 19 19 19 19  4  4  4  4  9  9  9  9 26
 26 26 26 26 26 26 31 31 31 31 31 31 31 31 31 31 31  0  0  0  0  0  0 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 10 10 10 10 10  2  2  2  2  2  2  2  2  2 36 36

In [6]:
#returns a numpy array representing the one-hot encoded version of the input data.
training_tags = to_categorical(training_tags)
print(training_tags)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
training_tags

In [7]:
# get only unique values from the input training_examples, with duplicates removed.
unique_values = set(training_examples)
print(len(unique_values))


395


In [9]:
#tokenize text data and convert it into sequences of integers to be used as input to neural network models.
toknizer =  Tokenizer(num_words= 395)
toknizer.fit_on_texts(training_examples)
sequance = toknizer.texts_to_sequences(training_examples)

In [23]:
sequance

[[161],
 [12, 9, 5],
 [1, 162, 24],
 [163],
 [68, 110],
 [164, 111],
 [12, 9, 165],
 [166],
 [167],
 [],
 [168],
 [112, 5],
 [88, 88],
 [112, 5, 113],
 [169],
 [15, 89, 170],
 [88],
 [29, 90, 68, 110],
 [171, 18, 5, 113],
 [172],
 [15, 173, 18, 174],
 [175],
 [3, 1, 4, 13, 6, 16, 60],
 [3, 1, 4, 13, 6, 16, 69],
 [3, 1, 4, 13, 6, 4, 60],
 [3, 1, 4, 13, 6, 4, 69],
 [19, 114, 5],
 [16, 60],
 [16, 69],
 [19, 9, 16, 60],
 [60],
 [5, 9, 91, 115],
 [5, 9, 91, 115, 176],
 [19, 114, 5],
 [19, 177, 5],
 [69],
 [19, 91, 5],
 [19, 178, 5],
 [13],
 [16, 13],
 [25, 5, 29, 90, 13],
 [3, 9, 5, 179],
 [3, 1, 16, 13],
 [3, 70, 15, 71, 5],
 [92, 16, 13],
 [3, 9, 5],
 [19, 9, 5],
 [19, 1, 180],
 [3, 89, 15, 181, 18],
 [19, 89, 15, 182, 18],
 [3, 9, 5],
 [49, 6, 2],
 [3, 1, 2, 49],
 [183, 184],
 [26, 9, 5, 116, 93],
 [3, 9, 16, 94],
 [94, 6, 185],
 [26, 1, 4, 2, 93],
 [2, 49],
 [3, 21, 2, 49],
 [1, 2, 93, 95, 186],
 [50, 117, 21, 2, 49],
 [3, 1, 4, 2, 94],
 [26, 70, 15, 187, 18, 2],
 [26, 70, 15, 188, 2],


In [10]:
# calculates the maximum length of sequences in the list sequance.
max(map(len, sequance))

9

In [11]:
#to pad sequences to a uniform length.
padded_sequence= pad_sequences(sequance, truncating='post', maxlen=38)

In [24]:
print(np.array(padded_sequence).shape)
print(training_tags.shape)
max_input_length = max(len(seq) for seq in padded_sequence)
print("Maximum input sequence length:", max_input_length)

(405, 38)
(405, 38)
Maximum input sequence length: 38


In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D


In [35]:
chat_model = Sequential() #create a sequential model.

#Embedding particularly for handling text data  
#It is responsible for converting integer-encoded representations of words into dense vectors of fixed size
chat_model.add(Embedding(405, 10, input_length=38)) 
chat_model.add(GlobalAveragePooling1D())
chat_model.add(Dense(300, activation='relu'))
chat_model.add(Dense(150, activation='relu'))
chat_model.add(Dense(200, activation='relu'))
chat_model.add(Dense(38, activation='softmax'))

In [36]:
chat_model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
chat_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 38, 10)            4050      
                                                                 
 global_average_pooling1d_2  (None, 10)                0         
  (GlobalAveragePooling1D)                                       
                                                                 
 dense_8 (Dense)             (None, 300)               3300      
                                                                 
 dense_9 (Dense)             (None, 150)               45150     
                                                                 
 dense_10 (Dense)            (None, 200)               30200     
                                                                 
 dense_11 (Dense)            (None, 38)                7638      
                                                      

In [40]:
history = chat_model.fit(np.array(padded_sequence), training_tags, epochs=300)

Epoch 1/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2446 - accuracy: 0.9111
Epoch 2/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2512 - accuracy: 0.9160
Epoch 3/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2411 - accuracy: 0.9185
Epoch 4/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2279 - accuracy: 0.9111
Epoch 5/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2660 - accuracy: 0.9136
Epoch 6/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2419 - accuracy: 0.9086
Epoch 7/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2207 - accuracy: 0.9259
Epoch 8/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2468 - accuracy: 0.9210
Epoch 9/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2288 - accuracy: 0.9210
Epoch 10/300
13/13 [==============================] - 0s 3ms/step - loss: 0.2268 - accuracy: 0.9210
Epoch 11/

In [41]:
chat_model.evaluate(np.array(padded_sequence), training_tags)

13/13 [==============================] - 0s 3ms/step - loss: 0.1370 - accuracy: 0.9556


[0.13697214424610138, 0.9555555582046509]

In [42]:
import pickle

#serializes and saves the toknizer
pickle.dump(toknizer, open("models/toknizer.pkl", 'wb'))
#serializes and saves the le (label encoder) object
pickle.dump(le, open('models/label_encoder.pkl', 'wb'))
#saves the chat model 
chat_model.save('models/chat_model.h5')

In [ ]:
from tempfile import NamedTemporaryFile
from tensorflow.keras.models import load_model
from flask import Flask, request, render_template

app = Flask(__name__)

model = load_model('models/chat_model.h5')

In [ ]:
@app.route('/')
def home():
  return render_template('home.html')


In [ ]:
@app.route('/',methods=['POST'])
def predict():

    #This line retrieves the value associated with the key "user" from the form data of the POST request.
    value=request.form.get("user") 

    #tokenizes the input text, and then pads the sequences to a maximum length of 38
    sent=pad_sequences(toknizer.texts_to_sequences([value]),maxlen=38) 

    # passes the padded sequence through the model to obtain predictions.
    # argmax is used to find the index of the maximum value in the prediction array.
    result=np.argmax(model.predict(np.array(sent)))
    
    #to convert the predicted index back to the original label.
    f_res=le.inverse_transform(np.array(result).reshape(1))

    #a random response from that tag is selected and stored in the output variable.
    output=''
    for tag in data['intents']:
        if tag['tag']== f_res:
            output=np.random.choice(tag['responses'])
            print(f_res)
    #send the result to the user
    return render_template('home.html', prediction_text='{} '.format(output))

In [ ]:
if __name__ == '__main__':
  app.run()
